collections:
  guide:
    title: Getting Started
    permalink: /guide/:title/
    active_prefix: /guide/
    output: true
  syncing:
    title: File Syncing
    permalink: /syncing/:title/
    active_prefix: /syncing/
    output: true
  editing:
    title: Editing
    permalink: /editing/:title/
    active_prefix: /editing/
    output: true
  tasks:
    title: Common Tasks
    permalink: /tasks/:title/
    active_prefix: /tasks/
    output: true
  sharing:
    title: Sharing
    permalink: /sharing/:title/
    active_prefix: /sharing/
    output: true
  jekyll:
    title: Jekyll
    permalink: /jekyll/:title/
    active_prefix: /jekyll/
    output: true
  extra:
    title: Extra
    permalink: /extra/:title/
    active_prefix: /extra/
    output: true
  issues:
    title: Known Issues
main_links:
  -
    title: Documentation
    link: /index.html
defaults:
- scope:
    path: ""
  values:
    layout: docs
