collections:
  overview:
    title: Overview
    permalink: /overview/:title/
    active_prefix: /overview/
    output: true
  getting_started:
    title: Getting Started
    permalink: /getting_started/:title/
    active_prefix: /getting_started/
    output: true
  syncing:
    title: File Syncing
    permalink: /syncing/:title/
    active_prefix: /syncing/
    output: true
  editing:
    title: Editing
    permalink: /editing/:title/
    active_prefix: /editing/
    output: true
  tasks:
    title: Common Tasks
    permalink: /tasks/:title/
    active_prefix: /tasks/
    output: true
  i18n:
    title: Internationalisation
    permalink: /i18n/:title/
    active_prefix: /i18n/
    output: true
  sharing:
    title: Sharing
    permalink: /sharing/:title/
    active_prefix: /sharing/
    output: true
  tutorials:
    title: Tutorials
    permalink: /tutorials/:title/
    active_prefix: /tutorials/
    output: true
  extra:
    title: Extra
    permalink: /extra/:title/
    active_prefix: /extra/
    output: true
main_links:
  -
    title: Documentation
    link: /index.html
defaults:
- scope:
    path: ""
  values:
    layout: docs
