name: CloudCannon Docs
version: 3.0.3
url: http://docs.cloudcannon.com
future: true

author:
  name: CloudCannon
  email: support@cloudcannon.com

collections:
  overview:
    title: Overview
    permalink: /overview/:title/
    active_prefix: overview
    output: true
  getting_started:
    title: Getting Started
    permalink: /getting_started/:title/
    active_prefix: getting_started
    output: true
  syncing:
    title: File Syncing
    permalink: /syncing/:title/
    active_prefix: syncing
    output: true
  building:
    title: Building
    permalink: /building/:title/
    active_prefix: building
    output: true
  editing:
    title: Editing
    permalink: /editing/:title/
    active_prefix: editing
    output: true
  domains:
    title: Domains
    permalink: /domains/:title/
    active_prefix: domains
    output: true
  hosting:
    title: Hosting
    permalink: /hosting/:title/
    active_prefix: hosting
    output: true
  sharing:
    title: Sharing
    permalink: /sharing/:title/
    active_prefix: sharing
    output: true
  authentication:
    title: Authentication
    permalink: /authentication/:title/
    active_prefix: authentication
    output: true
  i18n:
    title: Internationalisation
    permalink: /i18n/:title/
    active_prefix: i18n
    output: true
  tutorials:
    title: Tutorials
    permalink: /tutorials/:title/
    active_prefix: tutorials
    output: true

defaults:
- scope:
    path: ""
  values:
    layout: docs
